run:
  # default: '1m'
  timeout: '5m'

  # default: []
  build-tags:
    - 'all'

  # default: true
  skip-dirs-use-default: false

  # default: ''
  modules-download-mode: 'readonly'

  # default: false
  allow-parallel-runners: true

linters:
  enable:
    - 'asciicheck'
    - 'bodyclose'
    - 'deadcode'
    - 'depguard'
    - 'dogsled'
    - 'errcheck'
    - 'errorlint'
    - 'exportloopref'
    - 'gofmt'
    - 'gofumpt'
    - 'goheader'
    - 'goimports'
    - 'gomodguard'
    - 'goprintffuncname'
    - 'gosec'
    - 'gosimple'
    - 'govet'
    - 'ineffassign'
    - 'makezero'
    - 'misspell'
    - 'noctx'
    - 'paralleltest'
    - 'prealloc'
    - 'predeclared'
    - 'sqlclosecheck'
    - 'staticcheck'
    - 'structcheck'
    - 'stylecheck'
    - 'typecheck'
    - 'unconvert'
    - 'unused'
    - 'varcheck'
    - 'whitespace'

issues:
  # default: []
  exclude:
    - '^S1023:' # staticcheck: redundant returns help with http handlers
    - '^SA3000:' # staticcheck: not required in Go 11.4+
    - '^G102:' # gosec: to bind to all ifaces
    - '^G402:' # gosec: some services terminate at the load balancer
    - '^G401:' # gosec: use crypto/sha1
    - '^G505:' # gosec: use crypto/sha1
    - '^G108:' # profiling is available
    - '^Range statement' # paralleltest: false positives

  # default: 50
  max-issues-per-linter: 0

  # default: 3
  max-same-issues: 0

severity:
  # default: ''
  default-severity: error
